### PR TITLE
Fix null pointer for nonexistent item in Inventory commands

### PR DESCRIPTION
**Pull request by Zeli0**
Originally, the program would attempt to add null to the inventory when the provided item name didn't exist.
Let's address this.

### CODE REVIEW

**Review by jiexuanc — CHANGES_REQUESTED** [review]
The code now handles the case properly, however it is weird that Model would now depend on a class of logic/parser and that a parse exception should appear in a Model method. It is also more logical to have the name trimmed within the parser component instead of the model as that is the functionality of a paser

**Comment by Zeli0** [comment]
The new edits in these commits should address the changes brought up.

**Review by jiexuanc — COMMENTED** [review]
I believe an error should be thrown if the inventory do not contain the item to be deleted. Think the exception can be either implemented in Inventory class or logic/parser

**Comment by Zeli0** [comment]
Unsure if this was what you had in mind but this commit hopefully addresses the error.

**Comment by jiexuanc** [comment]
lgtm

**Pull request merged**
